version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  python:
    image: python:3.11-slim
    container_name: agribridge-python
    working_dir: /app
    volumes:
      - ./:/app:delegated
    command: sh -c "pip install --no-cache-dir -r python_service/requirements.txt && uvicorn python_service.app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo

  node:
    image: node:20
    container_name: agribridge-node
    working_dir: /app
    volumes:
      - ./:/app:delegated
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/agribridge
      - PYTHON_SERVICE_URL=http://python:8000
    depends_on:
      - python
      - mongo

volumes:
  mongo_data:
